name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: nixv-ubuntu
          path: target/release/nixv
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: target/release/nixv build

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: nixv-macos
          path: target/release/nixv
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: target/release/nixv build
